### ISSUE TITLE
Site seems to have stolen your blog ;=(

### ISSUE THREAD

**Issue by rustonaut** [theojulienne/blog-lab-scaling-accept#1]
https://newshimalaya.com/2020/07/04/scaling-linux-services-and-products-earlier-than-accepting-connections/

Btw. thanks for the Blog, I haven't read it yet but it seems to be what I'm looking for.

**Comment by theojulienne** [comment]
Thanks! It seems like a bunch of sites automatically ingest popular posts and repost them, oh well! I doubt it's worth chasing them down.
